<a href="https://colab.research.google.com/github/WhiteAndBlackFox/LearningPyTorch/blob/BasicConceptsAndStructuresPyTorch/BasicConceptsAndStructuresPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Основные понятия и структуры PyTorch

#### Подключаем библиотеки

In [1]:
import torch
from torch import FloatTensor, IntTensor
from torch.autograd import Variable

import numpy as np

#### Сразу определим, если есть видеокарта, то лучше на ней считать иначе на cpu все делаем

In [2]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cpu


## 1. Создание случайного FloatTensor размера 3x4x5

In [3]:
ft = FloatTensor(3, 4, 5, device=device)
print(ft)

tensor([[[-6.5823e-25,  3.0672e-41,  4.7644e-44,  0.0000e+00, -7.1622e-25],
         [ 3.0672e-41, -7.1622e-25,  3.0672e-41,  3.5733e-43,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  3.5733e-43,  0.0000e+00,  7.1466e-44,  0.0000e+00]],

        [[-7.1623e-25,  3.0672e-41, -7.1623e-25,  3.0672e-41,  3.5733e-43],
         [ 0.0000e+00,  8.8282e-44,  0.0000e+00, -7.1623e-25,  3.0672e-41],
         [-7.1623e-25,  3.0672e-41,  3.5733e-43,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 3.5733e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  3.5733e-43,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])


## 2. Посмотрим, какая форма получается

In [4]:
ft.shape

torch.Size([3, 4, 5])

## 3. Попробуем привести её к форме 6х10

In [5]:
ft = torch.reshape(ft, (6, 10))
print(ft)

tensor([[-6.5823e-25,  3.0672e-41,  4.7644e-44,  0.0000e+00, -7.1622e-25,
          3.0672e-41, -7.1622e-25,  3.0672e-41,  3.5733e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  3.5733e-43,  0.0000e+00,  7.1466e-44,  0.0000e+00],
        [-7.1623e-25,  3.0672e-41, -7.1623e-25,  3.0672e-41,  3.5733e-43,
          0.0000e+00,  8.8282e-44,  0.0000e+00, -7.1623e-25,  3.0672e-41],
        [-7.1623e-25,  3.0672e-41,  3.5733e-43,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 3.5733e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  3.5733e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


## 4. Попробуем создать случайный IntTensor размера 10

In [6]:
it = IntTensor(10, device=device)
print(it)

tensor([-1709294784,       21888,           1,           0,       65537,
           16843009,       65537,    16843009,           1,           0],
       dtype=torch.int32)


## 5. Попробуем перемножить FloatTensor на созданный IntTensor поэлементно

In [7]:
ft_mul_it = torch.mul(ft, it)
print(ft_mul_it)

tensor([[ 1.1251e-15,  6.7134e-37,  4.7644e-44,  0.0000e+00, -4.6939e-20,
          5.1660e-34, -4.6939e-20,  5.1660e-34,  3.5733e-43,  0.0000e+00],
        [-0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  2.3418e-38,  0.0000e+00,  7.1466e-44,  0.0000e+00],
        [ 1.2242e-15,  6.7134e-37, -7.1623e-25,  0.0000e+00,  2.3418e-38,
          0.0000e+00,  5.7857e-39,  0.0000e+00, -7.1623e-25,  0.0000e+00],
        [ 1.2242e-15,  6.7134e-37,  3.5733e-43,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-6.1078e-34,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  3.5733e-43,  0.0000e+00],
        [-0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


## 6. Попробуем умножить тензор матрично на себя, чтобы результат был размерности 6x6, без использования .dot

In [8]:
mm_ft = torch.matmul(ft_mul_it, ft_mul_it.T)
print(mm_ft)

tensor([[1.2659e-30, 0.0000e+00, 1.3774e-30, 1.3774e-30, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.3774e-30, 0.0000e+00, 1.4988e-30, 1.4988e-30, 0.0000e+00, 0.0000e+00],
        [1.3774e-30, 0.0000e+00, 1.4988e-30, 1.4988e-30, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


## 7. Посчитаем производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [9]:
x, z, t = [Variable(FloatTensor([i], device=device), requires_grad=True) for i in (1, 0.5, 2)]
y = x**3 + z + 75*t
y.backward()
print(y)

tensor([151.5000], grad_fn=<AddBackward0>)


## 8. Создадим единичный тензор размера 5x6

In [10]:
ot = torch.ones((5, 6), device=device)
print(ot)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


## 9. Переведем его в формат numpy

In [11]:
n_ot = ot.numpy()
print(n_ot, type(n_ot))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] <class 'numpy.ndarray'>
